// flow-typed signature: 70c0cf2fbcef0d23230938ff96c54c35
// flow-typed version: <<STUB>>/elasticlunr_v^0.9.5/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'elasticlunr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'elasticlunr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'elasticlunr/elasticlunr' {
  declare module.exports: any;
}

declare module 'elasticlunr/elasticlunr.min' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/app' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/elasticlunr' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/elasticlunr.min' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/index_builder' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/jquery' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/mustache' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/require' {
  declare module.exports: any;
}

declare module 'elasticlunr/example/text' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/configuration' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/document_store' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/elasticlunr' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/event_emitter' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/index' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/inverted_index' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/pipeline' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/sorted_set' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/stemmer' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/stop_word_filter' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/tokenizer' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/trimmer' {
  declare module.exports: any;
}

declare module 'elasticlunr/lib/utils' {
  declare module.exports: any;
}

declare module 'elasticlunr/release/elasticlunr' {
  declare module.exports: any;
}

declare module 'elasticlunr/release/elasticlunr.min' {
  declare module.exports: any;
}

declare module 'elasticlunr/server' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/configuration_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/document_store_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/elasticlunr_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/env/augment.min' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/env/jquery' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/env/qunit' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/env/runner' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/event_emitter_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/index_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/inverted_index_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/pipeline_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/search_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/serialisation_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/stemmer_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/stop_word_filter_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/test_helper' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/tokenizer_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/trimmer_test' {
  declare module.exports: any;
}

declare module 'elasticlunr/test/utils_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'elasticlunr/elasticlunr.js' {
  declare module.exports: $Exports<'elasticlunr/elasticlunr'>;
}
declare module 'elasticlunr/elasticlunr.min.js' {
  declare module.exports: $Exports<'elasticlunr/elasticlunr.min'>;
}
declare module 'elasticlunr/example/app.js' {
  declare module.exports: $Exports<'elasticlunr/example/app'>;
}
declare module 'elasticlunr/example/elasticlunr.js' {
  declare module.exports: $Exports<'elasticlunr/example/elasticlunr'>;
}
declare module 'elasticlunr/example/elasticlunr.min.js' {
  declare module.exports: $Exports<'elasticlunr/example/elasticlunr.min'>;
}
declare module 'elasticlunr/example/index_builder.js' {
  declare module.exports: $Exports<'elasticlunr/example/index_builder'>;
}
declare module 'elasticlunr/example/jquery.js' {
  declare module.exports: $Exports<'elasticlunr/example/jquery'>;
}
declare module 'elasticlunr/example/mustache.js' {
  declare module.exports: $Exports<'elasticlunr/example/mustache'>;
}
declare module 'elasticlunr/example/require.js' {
  declare module.exports: $Exports<'elasticlunr/example/require'>;
}
declare module 'elasticlunr/example/text.js' {
  declare module.exports: $Exports<'elasticlunr/example/text'>;
}
declare module 'elasticlunr/lib/configuration.js' {
  declare module.exports: $Exports<'elasticlunr/lib/configuration'>;
}
declare module 'elasticlunr/lib/document_store.js' {
  declare module.exports: $Exports<'elasticlunr/lib/document_store'>;
}
declare module 'elasticlunr/lib/elasticlunr.js' {
  declare module.exports: $Exports<'elasticlunr/lib/elasticlunr'>;
}
declare module 'elasticlunr/lib/event_emitter.js' {
  declare module.exports: $Exports<'elasticlunr/lib/event_emitter'>;
}
declare module 'elasticlunr/lib/index.js' {
  declare module.exports: $Exports<'elasticlunr/lib/index'>;
}
declare module 'elasticlunr/lib/inverted_index.js' {
  declare module.exports: $Exports<'elasticlunr/lib/inverted_index'>;
}
declare module 'elasticlunr/lib/pipeline.js' {
  declare module.exports: $Exports<'elasticlunr/lib/pipeline'>;
}
declare module 'elasticlunr/lib/sorted_set.js' {
  declare module.exports: $Exports<'elasticlunr/lib/sorted_set'>;
}
declare module 'elasticlunr/lib/stemmer.js' {
  declare module.exports: $Exports<'elasticlunr/lib/stemmer'>;
}
declare module 'elasticlunr/lib/stop_word_filter.js' {
  declare module.exports: $Exports<'elasticlunr/lib/stop_word_filter'>;
}
declare module 'elasticlunr/lib/tokenizer.js' {
  declare module.exports: $Exports<'elasticlunr/lib/tokenizer'>;
}
declare module 'elasticlunr/lib/trimmer.js' {
  declare module.exports: $Exports<'elasticlunr/lib/trimmer'>;
}
declare module 'elasticlunr/lib/utils.js' {
  declare module.exports: $Exports<'elasticlunr/lib/utils'>;
}
declare module 'elasticlunr/release/elasticlunr.js' {
  declare module.exports: $Exports<'elasticlunr/release/elasticlunr'>;
}
declare module 'elasticlunr/release/elasticlunr.min.js' {
  declare module.exports: $Exports<'elasticlunr/release/elasticlunr.min'>;
}
declare module 'elasticlunr/server.js' {
  declare module.exports: $Exports<'elasticlunr/server'>;
}
declare module 'elasticlunr/test/configuration_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/configuration_test'>;
}
declare module 'elasticlunr/test/document_store_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/document_store_test'>;
}
declare module 'elasticlunr/test/elasticlunr_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/elasticlunr_test'>;
}
declare module 'elasticlunr/test/env/augment.min.js' {
  declare module.exports: $Exports<'elasticlunr/test/env/augment.min'>;
}
declare module 'elasticlunr/test/env/jquery.js' {
  declare module.exports: $Exports<'elasticlunr/test/env/jquery'>;
}
declare module 'elasticlunr/test/env/qunit.js' {
  declare module.exports: $Exports<'elasticlunr/test/env/qunit'>;
}
declare module 'elasticlunr/test/env/runner.js' {
  declare module.exports: $Exports<'elasticlunr/test/env/runner'>;
}
declare module 'elasticlunr/test/event_emitter_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/event_emitter_test'>;
}
declare module 'elasticlunr/test/index_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/index_test'>;
}
declare module 'elasticlunr/test/inverted_index_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/inverted_index_test'>;
}
declare module 'elasticlunr/test/pipeline_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/pipeline_test'>;
}
declare module 'elasticlunr/test/search_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/search_test'>;
}
declare module 'elasticlunr/test/serialisation_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/serialisation_test'>;
}
declare module 'elasticlunr/test/stemmer_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/stemmer_test'>;
}
declare module 'elasticlunr/test/stop_word_filter_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/stop_word_filter_test'>;
}
declare module 'elasticlunr/test/test_helper.js' {
  declare module.exports: $Exports<'elasticlunr/test/test_helper'>;
}
declare module 'elasticlunr/test/tokenizer_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/tokenizer_test'>;
}
declare module 'elasticlunr/test/trimmer_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/trimmer_test'>;
}
declare module 'elasticlunr/test/utils_test.js' {
  declare module.exports: $Exports<'elasticlunr/test/utils_test'>;
}
