// flow-typed signature: c553c3e5f4c90cd514c3d9a80960f659
// flow-typed version: <<STUB>>/remark_v^10.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark/index' {
  declare module.exports: $Exports<'remark'>;
}
declare module 'remark/index.js' {
  declare module.exports: $Exports<'remark'>;
}
