// flow-typed signature: 1532fe07b947d0306c069a04fa829555
// flow-typed version: <<STUB>>/remark-grid-tables_v^1.1.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-grid-tables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-grid-tables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-grid-tables/dist/index' {
  declare module.exports: any;
}

declare module 'remark-grid-tables/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-grid-tables/dist/index.js' {
  declare module.exports: $Exports<'remark-grid-tables/dist/index'>;
}
declare module 'remark-grid-tables/src/index.js' {
  declare module.exports: $Exports<'remark-grid-tables/src/index'>;
}
