// flow-typed signature: c728a2683a18a29d40c038a250c56b5f
// flow-typed version: <<STUB>>/remark-strip-html_v^1.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-strip-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-strip-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-strip-html/index' {
  declare module.exports: $Exports<'remark-strip-html'>;
}
declare module 'remark-strip-html/index.js' {
  declare module.exports: $Exports<'remark-strip-html'>;
}
